import {test,expect} from '@playwright/test';
test('landing, survival movement, crafting, save round-trip and map',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#loading')).toBeHidden();await expect(page.locator('#start')).toBeVisible();await page.screenshot({path:'test-results/landing.png'});
 await page.locator('#start').click();await expect(page.locator('#hud')).toBeVisible();await page.waitForTimeout(300);await page.screenshot({path:'test-results/survival.png'});
 const before=await page.evaluate(()=>window.__hexwild.state.position);await page.keyboard.down('KeyW');await page.waitForTimeout(450);await page.keyboard.up('KeyW');const after=await page.evaluate(()=>window.__hexwild.state.position);expect(Math.hypot(after[0]-before[0],after[2]-before[2])).toBeGreaterThan(.1);
 await page.keyboard.press('KeyB');await expect(page.locator('#craft-overlay')).toBeVisible();await page.evaluate(()=>{window.__hexwild.give('wood',20);window.__hexwild.selectRecipe(0);});await page.locator('#craft-button').click();expect(await page.evaluate(()=>window.__hexwild.state.inventory.planks)).toBe(8);await page.locator('[data-recipe="2"]').click();await page.locator('#craft-button').click();expect(await page.evaluate(()=>window.__hexwild.state.tool)).toBe(1);await page.screenshot({path:'test-results/crafting.png'});
 await page.evaluate(()=>window.__hexwild.save());await page.reload();await page.locator('#continue').click();expect(await page.evaluate(()=>window.__hexwild.state.tool)).toBe(1);expect(await page.evaluate(()=>window.__hexwild.state.inventory.planks)).toBe(5);
 await page.keyboard.press('KeyM');await expect(page.locator('#map-overlay')).toBeVisible();await page.screenshot({path:'test-results/map.png'});expect(errors).toEqual([]);
});
test('farming, station requirements, food, chest and beacon victory',async({page})=>{
 await page.goto('/');await page.locator('#start').click();await page.evaluate(()=>{const g=window.__hexwild;g.give('hoe',1);g.give('seed',3);const w=g.state.world;g.setTarget({q:0,y:w.surface(0,0)-1,r:0,type:'grass'});g.interact();g.setTarget({q:0,y:w.surface(0,0)-1,r:0,type:'farmland'});g.interact();g.step(91);g.interact();});expect(await page.evaluate(()=>window.__hexwild.state.inventory.wheat)).toBe(2);
 await page.evaluate(()=>{const g=window.__hexwild;g.damage(5);g.give('bread',2);g.eat();});expect(await page.evaluate(()=>window.__hexwild.state.inventory.bread)).toBe(1);
 await page.evaluate(()=>{const g=window.__hexwild;g.give('crystal',9);g.give('stone',18);for(const b of g.state.world.beacons){g.teleport(b.q,b.y,b.r);g.setPlaying(true);g.interact();}});expect(await page.evaluate(()=>window.__hexwild.state.activated.length)).toBe(3);await expect(page.locator('#station-title')).toHaveText('初光，终于回来了。');
});
test('creative material palette and mobile layout',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await page.locator('#creative').click();await page.keyboard.press('KeyB');await expect(page.locator('#craft-overlay')).toBeVisible();await page.locator('[data-item="furnace"]').click();expect(await page.evaluate(()=>window.__hexwild.state.hotbar[0])).toBe('furnace');await page.screenshot({path:'test-results/mobile-crafting.png'});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);expect(overflow).toBe(false);});
