import {
  createElement,
  Pickaxe,
  Sword,
  Wheat,
  Beef,
  Sandwich,
  Flame,
  Orbit,
  Gem,
  Logs,
  BrickWall,
  BedDouble,
  Anvil,
  Fence,
  Mountain,
  CircleDot,
  Bean,
  Sprout,
  Snowflake,
  Hexagon,
  DoorOpen,
  Hammer,
  Package,
  Lamp,
  Cloud,
  Layers,
  TreePine,
  Leaf,
  Grid2X2,
  CookingPot,
  Apple,
  Axe,
  PaintBucket,
} from 'lucide';
import { ITEMS } from './core.js';

// Named imports keep the bundled icon set small; SVGs work offline on Pages.
const symbols = {
  emerald: Gem,
  bucket: PaintBucket,
  waterBucket: PaintBucket,
  lavaBucket: PaintBucket,
  glowBucket: PaintBucket,
  grass: Sprout,
  dirt: Layers,
  stone: Mountain,
  sand: Bean,
  wood: Logs,
  leaves: Leaf,
  planks: Fence,
  crystal: Gem,
  coal: Mountain,
  iron: Gem,
  brick: BrickWall,
  glass: Hexagon,
  lantern: Lamp,
  workbench: Hammer,
  furnace: CookingPot,
  chest: Package,
  bed: BedDouble,
  farmland: Grid2X2,
  snow: Snowflake,
  netherrack: Flame,
  basalt: Mountain,
  crimsonwood: TreePine,
  shroom: Cloud,
  glowstone: Lamp,
  endstone: CircleDot,
  obsidian: Layers,
  diamond: Gem,
  portal: DoorOpen,
  endportal: Orbit,
  bedrock: BrickWall,
  wool: Cloud,
  pick1: Pickaxe,
  pick2: Pickaxe,
  pick3: Pickaxe,
  pick4: Pickaxe,
  pearl: Orbit,
  ember: Flame,
  sword: Sword,
  hoe: Axe,
  ingot: Anvil,
  seed: Bean,
  wheat: Wheat,
  apple: Apple,
  bread: Sandwich,
  meat: Beef,
  cooked: Beef,
};
const cache = new Map();
export function itemIcon(id) {
  if (!cache.has(id)) {
    const svg = createElement(symbols[id] || Hexagon, {
      width: 24,
      height: 24,
      'stroke-width': 2.2,
      'aria-hidden': 'true',
      focusable: 'false',
    }).outerHTML;
    cache.set(
      id,
      `<span class="block-icon item-symbol" style="--block:${ITEMS[id]?.color || '#d5b778'}">${svg}</span>`,
    );
  }
  return cache.get(id);
}
